#ifndef PAL_HEADER_SOTP_FS
#define PAL_HEADER_SOTP_FS


#define PAL_USE_HW_ROT 1
#define PAL_USE_HW_RTC 0
#define PAL_USE_HW_TRNG 1
#define PAL_SIMULATOR_FLASH_OVER_FILE_SYSTEM 1
#define PAL_USE_SECURE_TIME 1


#endif //PAL_HEADER_SOTP_FS
